#!/bin/bash

#depends on some dbus sending plugin for thunderbird
#documented in i3pystatus modules

extract_data () {
    cut -d'"' -f2 <<< $@
}
NewMessageSignal () {
    MESSAGE=""
    read -r line #trash
    read -r line
    sender=$(extract_data $line)
    read -r line
    subject=$(extract_data $line)
    NUM_MAILS=$(( $NUM_MAILS + 1 ))
    notify-send "New mail from $sender" "$subject"
}
ChangedMessageSignal () {
    MESSAGE=""
    read -r line #trash
    read -r line
    TYPE=$(extract_data $line)
    if [[ $TYPE == "read" ]] ; then
        NUM_MAILS=$(( $NUM_MAILS - 1 ))
        NUM_MAILS=$(( 0 > $NUM_MAILS ? 0 : $NUM_MAILS )) #number of unread mails can't be nagative ;)
    elif [[ $TYPE == "unread" ]] ; then
        NUM_MAILS=$(( $NUM_MAILS + 1 ))
    fi
}
NUM_MAILS=0
interface="org.mozilla.thunderbird.DBus"
dbus-monitor "interface='$interface', type='signal'" |
while read -r line; do
    case $line in
        *ChangedMessageSignal)
            ChangedMessageSignal $line
            ;;
        *NewMessageSignal)
            NewMessageSignal $line
            ;;
        *)
            ;;
    esac
    echo "E ✉ $NUM_MAILS "
done


