#!/bin/bash
MPC_OUTPUT=$(mpc 2> /dev/null) || { echo "Mmpd not started";  exit; }
if [[ `wc -l <<< "$MPC_OUTPUT"` == "1" ]]; then
    POS=""
    ICON="◾"
else 
    SONG=$(sed -n 1p <<< "$MPC_OUTPUT" | tr -s ' ')
    LINE2=$(sed -n 2p <<< "$MPC_OUTPUT" | tr -s ' ')
    POS=`cut -d' ' -f3 <<< $LINE2`
    STATUS=`cut -d' ' -f1 <<< $LINE2`
    if [[ $STATUS == "[playing]" ]] ; then
        ICON="▶"
    elif [[ $STATUS == "[paused]" ]] ; then
        ICON="▷"
    fi
fi
trap : SIGTERM SIGINT
if [[ $STATUS == "[playing]" ]]; then
    zscroll -n -l 20 -b "M $ICON " "$SONG " -a "[$POS] " &
    ZSCROLL_PID=$!
    wait $ZSCROLL_PID
    if [[ $? -gt 128 ]]
    then
        kill $ZSCROLL_PID
    fi
    exit 0
else
    echo "M $ICON ${SONG:0:20}[$POS] "
    exit 0
fi
